/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedByLoginRouteRouteImport } from './routes/_protected-by-login/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ProtectedByLoginTwoFactorRouteImport } from './routes/_protected-by-login/two-factor'
import { Route as ProtectedByLoginNoBybitApiKeyRouteImport } from './routes/_protected-by-login/no-bybit-api-key'
import { Route as ProtectedByLoginApiKeysRouteImport } from './routes/_protected-by-login/api-keys'
import { Route as AuthTwoFactorVerifyRouteImport } from './routes/_auth/two-factor-verify'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ProtectedByLoginProtectedByBybitRouteRouteImport } from './routes/_protected-by-login/_protected-by-bybit/route'
import { Route as ProtectedByLoginProtectedByBybitIndexRouteImport } from './routes/_protected-by-login/_protected-by-bybit/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedByLoginProtectedByBybitOrdersRouteImport } from './routes/_protected-by-login/_protected-by-bybit/orders'
import { Route as ProtectedByLoginProtectedByBybitHistoryRouteImport } from './routes/_protected-by-login/_protected-by-bybit/history'
import { Route as ProtectedByLoginProtectedByBybitChartRouteImport } from './routes/_protected-by-login/_protected-by-bybit/chart'

const ProtectedByLoginRouteRoute = ProtectedByLoginRouteRouteImport.update({
  id: '/_protected-by-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedByLoginTwoFactorRoute =
  ProtectedByLoginTwoFactorRouteImport.update({
    id: '/two-factor',
    path: '/two-factor',
    getParentRoute: () => ProtectedByLoginRouteRoute,
  } as any)
const ProtectedByLoginNoBybitApiKeyRoute =
  ProtectedByLoginNoBybitApiKeyRouteImport.update({
    id: '/no-bybit-api-key',
    path: '/no-bybit-api-key',
    getParentRoute: () => ProtectedByLoginRouteRoute,
  } as any)
const ProtectedByLoginApiKeysRoute = ProtectedByLoginApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedByLoginRouteRoute,
} as any)
const AuthTwoFactorVerifyRoute = AuthTwoFactorVerifyRouteImport.update({
  id: '/two-factor-verify',
  path: '/two-factor-verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedByLoginProtectedByBybitRouteRoute =
  ProtectedByLoginProtectedByBybitRouteRouteImport.update({
    id: '/_protected-by-bybit',
    getParentRoute: () => ProtectedByLoginRouteRoute,
  } as any)
const ProtectedByLoginProtectedByBybitIndexRoute =
  ProtectedByLoginProtectedByBybitIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedByLoginProtectedByBybitRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedByLoginProtectedByBybitOrdersRoute =
  ProtectedByLoginProtectedByBybitOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => ProtectedByLoginProtectedByBybitRouteRoute,
  } as any)
const ProtectedByLoginProtectedByBybitHistoryRoute =
  ProtectedByLoginProtectedByBybitHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProtectedByLoginProtectedByBybitRouteRoute,
  } as any)
const ProtectedByLoginProtectedByBybitChartRoute =
  ProtectedByLoginProtectedByBybitChartRouteImport.update({
    id: '/chart',
    path: '/chart',
    getParentRoute: () => ProtectedByLoginProtectedByBybitRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedByLoginProtectedByBybitIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/two-factor-verify': typeof AuthTwoFactorVerifyRoute
  '/api-keys': typeof ProtectedByLoginApiKeysRoute
  '/no-bybit-api-key': typeof ProtectedByLoginNoBybitApiKeyRoute
  '/two-factor': typeof ProtectedByLoginTwoFactorRoute
  '/chart': typeof ProtectedByLoginProtectedByBybitChartRoute
  '/history': typeof ProtectedByLoginProtectedByBybitHistoryRoute
  '/orders': typeof ProtectedByLoginProtectedByBybitOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedByLoginProtectedByBybitIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/two-factor-verify': typeof AuthTwoFactorVerifyRoute
  '/api-keys': typeof ProtectedByLoginApiKeysRoute
  '/no-bybit-api-key': typeof ProtectedByLoginNoBybitApiKeyRoute
  '/two-factor': typeof ProtectedByLoginTwoFactorRoute
  '/chart': typeof ProtectedByLoginProtectedByBybitChartRoute
  '/history': typeof ProtectedByLoginProtectedByBybitHistoryRoute
  '/orders': typeof ProtectedByLoginProtectedByBybitOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected-by-login': typeof ProtectedByLoginRouteRouteWithChildren
  '/_protected-by-login/_protected-by-bybit': typeof ProtectedByLoginProtectedByBybitRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/two-factor-verify': typeof AuthTwoFactorVerifyRoute
  '/_protected-by-login/api-keys': typeof ProtectedByLoginApiKeysRoute
  '/_protected-by-login/no-bybit-api-key': typeof ProtectedByLoginNoBybitApiKeyRoute
  '/_protected-by-login/two-factor': typeof ProtectedByLoginTwoFactorRoute
  '/_protected-by-login/_protected-by-bybit/chart': typeof ProtectedByLoginProtectedByBybitChartRoute
  '/_protected-by-login/_protected-by-bybit/history': typeof ProtectedByLoginProtectedByBybitHistoryRoute
  '/_protected-by-login/_protected-by-bybit/orders': typeof ProtectedByLoginProtectedByBybitOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected-by-login/_protected-by-bybit/': typeof ProtectedByLoginProtectedByBybitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/two-factor-verify'
    | '/api-keys'
    | '/no-bybit-api-key'
    | '/two-factor'
    | '/chart'
    | '/history'
    | '/orders'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/two-factor-verify'
    | '/api-keys'
    | '/no-bybit-api-key'
    | '/two-factor'
    | '/chart'
    | '/history'
    | '/orders'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected-by-login'
    | '/_protected-by-login/_protected-by-bybit'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/two-factor-verify'
    | '/_protected-by-login/api-keys'
    | '/_protected-by-login/no-bybit-api-key'
    | '/_protected-by-login/two-factor'
    | '/_protected-by-login/_protected-by-bybit/chart'
    | '/_protected-by-login/_protected-by-bybit/history'
    | '/_protected-by-login/_protected-by-bybit/orders'
    | '/api/auth/$'
    | '/_protected-by-login/_protected-by-bybit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedByLoginRouteRoute: typeof ProtectedByLoginRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected-by-login': {
      id: '/_protected-by-login'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedByLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected-by-login/two-factor': {
      id: '/_protected-by-login/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof ProtectedByLoginTwoFactorRouteImport
      parentRoute: typeof ProtectedByLoginRouteRoute
    }
    '/_protected-by-login/no-bybit-api-key': {
      id: '/_protected-by-login/no-bybit-api-key'
      path: '/no-bybit-api-key'
      fullPath: '/no-bybit-api-key'
      preLoaderRoute: typeof ProtectedByLoginNoBybitApiKeyRouteImport
      parentRoute: typeof ProtectedByLoginRouteRoute
    }
    '/_protected-by-login/api-keys': {
      id: '/_protected-by-login/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedByLoginApiKeysRouteImport
      parentRoute: typeof ProtectedByLoginRouteRoute
    }
    '/_auth/two-factor-verify': {
      id: '/_auth/two-factor-verify'
      path: '/two-factor-verify'
      fullPath: '/two-factor-verify'
      preLoaderRoute: typeof AuthTwoFactorVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected-by-login/_protected-by-bybit': {
      id: '/_protected-by-login/_protected-by-bybit'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitRouteRouteImport
      parentRoute: typeof ProtectedByLoginRouteRoute
    }
    '/_protected-by-login/_protected-by-bybit/': {
      id: '/_protected-by-login/_protected-by-bybit/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitIndexRouteImport
      parentRoute: typeof ProtectedByLoginProtectedByBybitRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected-by-login/_protected-by-bybit/orders': {
      id: '/_protected-by-login/_protected-by-bybit/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitOrdersRouteImport
      parentRoute: typeof ProtectedByLoginProtectedByBybitRouteRoute
    }
    '/_protected-by-login/_protected-by-bybit/history': {
      id: '/_protected-by-login/_protected-by-bybit/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitHistoryRouteImport
      parentRoute: typeof ProtectedByLoginProtectedByBybitRouteRoute
    }
    '/_protected-by-login/_protected-by-bybit/chart': {
      id: '/_protected-by-login/_protected-by-bybit/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitChartRouteImport
      parentRoute: typeof ProtectedByLoginProtectedByBybitRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorVerifyRoute: typeof AuthTwoFactorVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorVerifyRoute: AuthTwoFactorVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedByLoginProtectedByBybitRouteRouteChildren {
  ProtectedByLoginProtectedByBybitChartRoute: typeof ProtectedByLoginProtectedByBybitChartRoute
  ProtectedByLoginProtectedByBybitHistoryRoute: typeof ProtectedByLoginProtectedByBybitHistoryRoute
  ProtectedByLoginProtectedByBybitOrdersRoute: typeof ProtectedByLoginProtectedByBybitOrdersRoute
  ProtectedByLoginProtectedByBybitIndexRoute: typeof ProtectedByLoginProtectedByBybitIndexRoute
}

const ProtectedByLoginProtectedByBybitRouteRouteChildren: ProtectedByLoginProtectedByBybitRouteRouteChildren =
  {
    ProtectedByLoginProtectedByBybitChartRoute:
      ProtectedByLoginProtectedByBybitChartRoute,
    ProtectedByLoginProtectedByBybitHistoryRoute:
      ProtectedByLoginProtectedByBybitHistoryRoute,
    ProtectedByLoginProtectedByBybitOrdersRoute:
      ProtectedByLoginProtectedByBybitOrdersRoute,
    ProtectedByLoginProtectedByBybitIndexRoute:
      ProtectedByLoginProtectedByBybitIndexRoute,
  }

const ProtectedByLoginProtectedByBybitRouteRouteWithChildren =
  ProtectedByLoginProtectedByBybitRouteRoute._addFileChildren(
    ProtectedByLoginProtectedByBybitRouteRouteChildren,
  )

interface ProtectedByLoginRouteRouteChildren {
  ProtectedByLoginProtectedByBybitRouteRoute: typeof ProtectedByLoginProtectedByBybitRouteRouteWithChildren
  ProtectedByLoginApiKeysRoute: typeof ProtectedByLoginApiKeysRoute
  ProtectedByLoginNoBybitApiKeyRoute: typeof ProtectedByLoginNoBybitApiKeyRoute
  ProtectedByLoginTwoFactorRoute: typeof ProtectedByLoginTwoFactorRoute
}

const ProtectedByLoginRouteRouteChildren: ProtectedByLoginRouteRouteChildren = {
  ProtectedByLoginProtectedByBybitRouteRoute:
    ProtectedByLoginProtectedByBybitRouteRouteWithChildren,
  ProtectedByLoginApiKeysRoute: ProtectedByLoginApiKeysRoute,
  ProtectedByLoginNoBybitApiKeyRoute: ProtectedByLoginNoBybitApiKeyRoute,
  ProtectedByLoginTwoFactorRoute: ProtectedByLoginTwoFactorRoute,
}

const ProtectedByLoginRouteRouteWithChildren =
  ProtectedByLoginRouteRoute._addFileChildren(
    ProtectedByLoginRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedByLoginRouteRoute: ProtectedByLoginRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
