/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ProtectedByLoginRouteRouteImport } from './pages/_protected-by-login/route'
import { Route as AuthRegisterRouteImport } from './pages/auth/register'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as ProtectedByLoginTwoFactorRouteImport } from './pages/_protected-by-login/two-factor'
import { Route as ProtectedByLoginNoBybitApiKeyRouteImport } from './pages/_protected-by-login/no-bybit-api-key'
import { Route as ProtectedByLoginApiKeysRouteImport } from './pages/_protected-by-login/api-keys'
import { Route as ProtectedByLoginProtectedByBybitRouteRouteImport } from './pages/_protected-by-login/_protected-by-bybit/route'
import { Route as ProtectedByLoginProtectedByBybitIndexRouteImport } from './pages/_protected-by-login/_protected-by-bybit/index'
import { Route as ApiAuthSplatRouteImport } from './pages/api/auth/$'
import { Route as ProtectedByLoginProtectedByBybitOrdersRouteImport } from './pages/_protected-by-login/_protected-by-bybit/orders'
import { Route as ProtectedByLoginProtectedByBybitHistoryRouteImport } from './pages/_protected-by-login/_protected-by-bybit/history'
import { Route as ProtectedByLoginProtectedByBybitChartRouteImport } from './pages/_protected-by-login/_protected-by-bybit/chart'

const ProtectedByLoginRouteRoute = ProtectedByLoginRouteRouteImport.update({
  id: '/_protected-by-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedByLoginTwoFactorRoute =
  ProtectedByLoginTwoFactorRouteImport.update({
    id: '/two-factor',
    path: '/two-factor',
    getParentRoute: () => ProtectedByLoginRouteRoute,
  } as any)
const ProtectedByLoginNoBybitApiKeyRoute =
  ProtectedByLoginNoBybitApiKeyRouteImport.update({
    id: '/no-bybit-api-key',
    path: '/no-bybit-api-key',
    getParentRoute: () => ProtectedByLoginRouteRoute,
  } as any)
const ProtectedByLoginApiKeysRoute = ProtectedByLoginApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedByLoginRouteRoute,
} as any)
const ProtectedByLoginProtectedByBybitRouteRoute =
  ProtectedByLoginProtectedByBybitRouteRouteImport.update({
    id: '/_protected-by-bybit',
    getParentRoute: () => ProtectedByLoginRouteRoute,
  } as any)
const ProtectedByLoginProtectedByBybitIndexRoute =
  ProtectedByLoginProtectedByBybitIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedByLoginProtectedByBybitRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedByLoginProtectedByBybitOrdersRoute =
  ProtectedByLoginProtectedByBybitOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => ProtectedByLoginProtectedByBybitRouteRoute,
  } as any)
const ProtectedByLoginProtectedByBybitHistoryRoute =
  ProtectedByLoginProtectedByBybitHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProtectedByLoginProtectedByBybitRouteRoute,
  } as any)
const ProtectedByLoginProtectedByBybitChartRoute =
  ProtectedByLoginProtectedByBybitChartRouteImport.update({
    id: '/chart',
    path: '/chart',
    getParentRoute: () => ProtectedByLoginProtectedByBybitRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedByLoginProtectedByBybitIndexRoute
  '/api-keys': typeof ProtectedByLoginApiKeysRoute
  '/no-bybit-api-key': typeof ProtectedByLoginNoBybitApiKeyRoute
  '/two-factor': typeof ProtectedByLoginTwoFactorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chart': typeof ProtectedByLoginProtectedByBybitChartRoute
  '/history': typeof ProtectedByLoginProtectedByBybitHistoryRoute
  '/orders': typeof ProtectedByLoginProtectedByBybitOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedByLoginProtectedByBybitIndexRoute
  '/api-keys': typeof ProtectedByLoginApiKeysRoute
  '/no-bybit-api-key': typeof ProtectedByLoginNoBybitApiKeyRoute
  '/two-factor': typeof ProtectedByLoginTwoFactorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chart': typeof ProtectedByLoginProtectedByBybitChartRoute
  '/history': typeof ProtectedByLoginProtectedByBybitHistoryRoute
  '/orders': typeof ProtectedByLoginProtectedByBybitOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected-by-login': typeof ProtectedByLoginRouteRouteWithChildren
  '/_protected-by-login/_protected-by-bybit': typeof ProtectedByLoginProtectedByBybitRouteRouteWithChildren
  '/_protected-by-login/api-keys': typeof ProtectedByLoginApiKeysRoute
  '/_protected-by-login/no-bybit-api-key': typeof ProtectedByLoginNoBybitApiKeyRoute
  '/_protected-by-login/two-factor': typeof ProtectedByLoginTwoFactorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_protected-by-login/_protected-by-bybit/chart': typeof ProtectedByLoginProtectedByBybitChartRoute
  '/_protected-by-login/_protected-by-bybit/history': typeof ProtectedByLoginProtectedByBybitHistoryRoute
  '/_protected-by-login/_protected-by-bybit/orders': typeof ProtectedByLoginProtectedByBybitOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected-by-login/_protected-by-bybit/': typeof ProtectedByLoginProtectedByBybitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/no-bybit-api-key'
    | '/two-factor'
    | '/auth/login'
    | '/auth/register'
    | '/chart'
    | '/history'
    | '/orders'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/no-bybit-api-key'
    | '/two-factor'
    | '/auth/login'
    | '/auth/register'
    | '/chart'
    | '/history'
    | '/orders'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_protected-by-login'
    | '/_protected-by-login/_protected-by-bybit'
    | '/_protected-by-login/api-keys'
    | '/_protected-by-login/no-bybit-api-key'
    | '/_protected-by-login/two-factor'
    | '/auth/login'
    | '/auth/register'
    | '/_protected-by-login/_protected-by-bybit/chart'
    | '/_protected-by-login/_protected-by-bybit/history'
    | '/_protected-by-login/_protected-by-bybit/orders'
    | '/api/auth/$'
    | '/_protected-by-login/_protected-by-bybit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedByLoginRouteRoute: typeof ProtectedByLoginRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected-by-login': {
      id: '/_protected-by-login'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedByLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected-by-login/two-factor': {
      id: '/_protected-by-login/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof ProtectedByLoginTwoFactorRouteImport
      parentRoute: typeof ProtectedByLoginRouteRoute
    }
    '/_protected-by-login/no-bybit-api-key': {
      id: '/_protected-by-login/no-bybit-api-key'
      path: '/no-bybit-api-key'
      fullPath: '/no-bybit-api-key'
      preLoaderRoute: typeof ProtectedByLoginNoBybitApiKeyRouteImport
      parentRoute: typeof ProtectedByLoginRouteRoute
    }
    '/_protected-by-login/api-keys': {
      id: '/_protected-by-login/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedByLoginApiKeysRouteImport
      parentRoute: typeof ProtectedByLoginRouteRoute
    }
    '/_protected-by-login/_protected-by-bybit': {
      id: '/_protected-by-login/_protected-by-bybit'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitRouteRouteImport
      parentRoute: typeof ProtectedByLoginRouteRoute
    }
    '/_protected-by-login/_protected-by-bybit/': {
      id: '/_protected-by-login/_protected-by-bybit/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitIndexRouteImport
      parentRoute: typeof ProtectedByLoginProtectedByBybitRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected-by-login/_protected-by-bybit/orders': {
      id: '/_protected-by-login/_protected-by-bybit/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitOrdersRouteImport
      parentRoute: typeof ProtectedByLoginProtectedByBybitRouteRoute
    }
    '/_protected-by-login/_protected-by-bybit/history': {
      id: '/_protected-by-login/_protected-by-bybit/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitHistoryRouteImport
      parentRoute: typeof ProtectedByLoginProtectedByBybitRouteRoute
    }
    '/_protected-by-login/_protected-by-bybit/chart': {
      id: '/_protected-by-login/_protected-by-bybit/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ProtectedByLoginProtectedByBybitChartRouteImport
      parentRoute: typeof ProtectedByLoginProtectedByBybitRouteRoute
    }
  }
}

interface ProtectedByLoginProtectedByBybitRouteRouteChildren {
  ProtectedByLoginProtectedByBybitChartRoute: typeof ProtectedByLoginProtectedByBybitChartRoute
  ProtectedByLoginProtectedByBybitHistoryRoute: typeof ProtectedByLoginProtectedByBybitHistoryRoute
  ProtectedByLoginProtectedByBybitOrdersRoute: typeof ProtectedByLoginProtectedByBybitOrdersRoute
  ProtectedByLoginProtectedByBybitIndexRoute: typeof ProtectedByLoginProtectedByBybitIndexRoute
}

const ProtectedByLoginProtectedByBybitRouteRouteChildren: ProtectedByLoginProtectedByBybitRouteRouteChildren =
  {
    ProtectedByLoginProtectedByBybitChartRoute:
      ProtectedByLoginProtectedByBybitChartRoute,
    ProtectedByLoginProtectedByBybitHistoryRoute:
      ProtectedByLoginProtectedByBybitHistoryRoute,
    ProtectedByLoginProtectedByBybitOrdersRoute:
      ProtectedByLoginProtectedByBybitOrdersRoute,
    ProtectedByLoginProtectedByBybitIndexRoute:
      ProtectedByLoginProtectedByBybitIndexRoute,
  }

const ProtectedByLoginProtectedByBybitRouteRouteWithChildren =
  ProtectedByLoginProtectedByBybitRouteRoute._addFileChildren(
    ProtectedByLoginProtectedByBybitRouteRouteChildren,
  )

interface ProtectedByLoginRouteRouteChildren {
  ProtectedByLoginProtectedByBybitRouteRoute: typeof ProtectedByLoginProtectedByBybitRouteRouteWithChildren
  ProtectedByLoginApiKeysRoute: typeof ProtectedByLoginApiKeysRoute
  ProtectedByLoginNoBybitApiKeyRoute: typeof ProtectedByLoginNoBybitApiKeyRoute
  ProtectedByLoginTwoFactorRoute: typeof ProtectedByLoginTwoFactorRoute
}

const ProtectedByLoginRouteRouteChildren: ProtectedByLoginRouteRouteChildren = {
  ProtectedByLoginProtectedByBybitRouteRoute:
    ProtectedByLoginProtectedByBybitRouteRouteWithChildren,
  ProtectedByLoginApiKeysRoute: ProtectedByLoginApiKeysRoute,
  ProtectedByLoginNoBybitApiKeyRoute: ProtectedByLoginNoBybitApiKeyRoute,
  ProtectedByLoginTwoFactorRoute: ProtectedByLoginTwoFactorRoute,
}

const ProtectedByLoginRouteRouteWithChildren =
  ProtectedByLoginRouteRoute._addFileChildren(
    ProtectedByLoginRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  ProtectedByLoginRouteRoute: ProtectedByLoginRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './app/router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
